/** 名單測試案例。每個網域多位訂閱者，熱門平台更多。名稱是一般人名，信箱本地部分對應人名。 */

export interface MailCase {
  brand: string;
  domain: string;
  group: string;
  /** 名稱裡再帶一個分類，讓「中國信箱」也能找到放在常見裡的 QQ、163。 */
  also?: string;
}

function rows(group: string, items: Array<[string, string] | [string, string, string]>): MailCase[] {
  return items.map(([brand, domain, also]) => ({
    brand,
    domain: domain.toLowerCase(),
    group,
    ...(also ? { also } : {}),
  }));
}

export const MAIL_CASES: MailCase[] = [
  ...rows('常見信箱', [
    ['Gmail', 'gmail.com'],
    ['Googlemail', 'googlemail.com'],
    ['Outlook', 'outlook.com'],
    ['Hotmail', 'hotmail.com'],
    ['Live', 'live.com'],
    ['MSN', 'msn.com'],
    ['Yahoo', 'yahoo.com'],
    ['Ymail', 'ymail.com'],
    ['Rocketmail', 'rocketmail.com'],
    ['iCloud', 'icloud.com'],
    ['Me.com', 'me.com'],
    ['Mac.com', 'mac.com'],
    ['AOL', 'aol.com'],
    ['AIM', 'aim.com'],
    ['GMX', 'gmx.com'],
    ['Mail.com', 'mail.com'],
    ['Zoho', 'zoho.com'],
    ['Zoho Mail', 'zohomail.com'],
    ['Proton', 'proton.me', '隱私信箱'],
    ['Yandex', 'yandex.com'],
    ['QQ', 'qq.com', '中國信箱'],
    ['163', '163.com', '中國信箱'],
  ]),
  ...rows('少見信箱', [
    ['Hey', 'hey.com'],
    ['Fastmail', 'fastmail.com'],
    ['Fastmail FM', 'fastmail.fm'],
    ['Pobox', 'pobox.com'],
    ['Runbox', 'runbox.com'],
    ['Hushmail', 'hushmail.com'],
    ['CounterMail', 'countermail.com'],
    ['Mailfence', 'mailfence.com'],
    ['StartMail', 'startmail.com'],
    ['Kolab Now', 'kolabnow.com'],
    ['CTemplar', 'ctemplar.com'],
    ['Skiff', 'skiff.com'],
    ['Excite', 'excite.com'],
    ['Lycos', 'lycos.com'],
    ['Netscape', 'netscape.net'],
    ['Juno', 'juno.com'],
    ['NetZero', 'netzero.net'],
    ['CompuServe', 'compuserve.com'],
    ['Mail.ru', 'mail.ru'],
    ['Inbox.com', 'inbox.com'],
    ['Email.com', 'email.com'],
    ['Consultant.com', 'consultant.com'],
    ['Engineer.com', 'engineer.com'],
    ['Doctor.com', 'doctor.com'],
    ['Musician.org', 'musician.org'],
    ['Techie.com', 'techie.com'],
    ['Post.com', 'post.com'],
    ['Myself.com', 'myself.com'],
    ['USA.com', 'usa.com'],
    ['Asia.com', 'asia.com'],
    ['Europe.com', 'europe.com'],
    ['London.com', 'london.com'],
    ['Accountant.com', 'accountant.com'],
    ['Lawyer.com', 'lawyer.com'],
    ['Programmer.net', 'programmer.net'],
    ['Cheerful.com', 'cheerful.com'],
    ['Writeme.com', 'writeme.com'],
    ['Dr.com', 'dr.com'],
    ['Iname.com', 'iname.com'],
  ]),
  ...rows('中國信箱', [
    ['Foxmail', 'foxmail.com'],
    ['QQ VIP', 'vip.qq.com'],
    ['騰訊企業郵', 'exmail.qq.com'],
    ['網易 126', '126.com'],
    ['網易 Yeah', 'yeah.net'],
    ['網易 188', '188.com'],
    ['163 VIP', 'vip.163.com'],
    ['126 VIP', 'vip.126.com'],
    ['網易企業郵', 'qiye.163.com'],
    ['新浪', 'sina.com'],
    ['新浪中國', 'sina.cn'],
    ['新浪 VIP', 'vip.sina.com'],
    ['搜狐', 'sohu.com'],
    ['搜狐 VIP', 'vip.sohu.com'],
    ['中國移動 139', '139.com'],
    ['中國電信 189', '189.cn'],
    ['聯通沃', 'wo.cn'],
    ['聯通郵箱', 'wo.com.cn'],
    ['21CN', '21cn.com'],
    ['TOM', 'tom.com'],
    ['TOM VIP', 'vip.tom.com'],
    ['263', '263.net'],
    ['億郵', 'eyou.com'],
    ['億唐', 'etang.com'],
    ['藝龍', 'elong.com'],
    ['ChinaRen', 'chinaren.com'],
    ['中華網', 'china.com'],
    ['上海熱線', 'online.sh.cn'],
    ['熱線 citiz', 'citiz.net'],
    ['371', '371.net'],
    ['和訊', 'hexun.com'],
    ['搜狗', 'sogou.com'],
    ['阿里雲郵', 'aliyun.com'],
    ['2980', '2980.com'],
    ['Live 中國', 'live.cn'],
    ['MSN 中國', 'msn.cn'],
  ]),
  ...rows('台灣信箱', [
    ['Yahoo 奇摩', 'yahoo.com.tw'],
    ['Kimo', 'kimo.com'],
    ['中華電信', 'hinet.net'],
    ['Hinet 信箱', 'msa.hinet.net'],
    ['Hinet ms7', 'ms7.hinet.net'],
    ['Hinet ms15', 'ms15.hinet.net'],
    ['Hinet ms24', 'ms24.hinet.net'],
    ['Hinet ms36', 'ms36.hinet.net'],
    ['Hinet ms41', 'ms41.hinet.net'],
    ['Hinet ms51', 'ms51.hinet.net'],
    ['Hinet ms66', 'ms66.hinet.net'],
    ['Hinet ms74', 'ms74.hinet.net'],
    ['Hinet ms88', 'ms88.hinet.net'],
    ['種子網路', 'seed.net.tw'],
    ['PChome', 'pchome.com.tw'],
    ['Yam', 'yam.com'],
    ['So-net 台灣', 'so-net.net.tw'],
    ['和信', 'giga.net.tw'],
    ['優必達', 'url.com.tw'],
    ['亞太', 'apol.com.tw'],
    ['Mail2000', 'mail2000.com.tw'],
    ['台灣固網', 'tfn.net.tw'],
    ['LiveMail', 'livemail.tw'],
  ]),
  ...rows('香港信箱', [
    ['Yahoo 香港', 'yahoo.com.hk'],
    ['網上行', 'netvigator.com'],
    ['網上行商務', 'biznetvigator.com'],
    ['香港星光', 'hkstar.com'],
    ['HKNet', 'hknet.com'],
    ['Pacific 香港', 'pacific.net.hk'],
    ['城市電訊', 'ctimail.com'],
    ['香港寬頻', 'hkbn.net'],
    ['有線寬頻', 'i-cable.com'],
    ['SmarTone', 'smartone.com'],
    ['3 香港', 'three.com.hk'],
    ['和記', 'hutchcity.com'],
    ['Hotmail 香港', 'hotmail.com.hk'],
    ['Live 香港', 'live.hk'],
  ]),
  ...rows('日本信箱', [
    ['Yahoo 日本', 'yahoo.co.jp'],
    ['docomo', 'docomo.ne.jp'],
    ['au', 'ezweb.ne.jp'],
    ['au.com', 'au.com'],
    ['SoftBank', 'softbank.ne.jp'],
    ['i.softbank', 'i.softbank.jp'],
    ['Y!mobile', 'ymobile.ne.jp'],
    ['Vodafone 日本', 'vodafone.ne.jp'],
    ['Yahoo 手機', 'yahoo.ne.jp'],
    ['WILLCOM', 'willcom.com'],
    ['Disney Mobile', 'disney.ne.jp'],
    ['EMOBILE', 'emobile.ne.jp'],
    ['nifty', 'nifty.com'],
    ['OCN', 'ocn.ne.jp'],
    ['ぷらら', 'plala.or.jp'],
    ['So-net 日本', 'so-net.ne.jp'],
    ['BIGLOBE', 'biglobe.ne.jp'],
    ['DION', 'dion.ne.jp'],
    ['Infoseek', 'infoseek.jp'],
    ['excite 日本', 'excite.co.jp'],
    ['livedoor', 'livedoor.com'],
    ['goo', 'goo.jp'],
    ['Yahoo BB', 'ybb.ne.jp'],
    ['J:COM', 'jcom.zaq.ne.jp'],
    ['eo', 'eonet.ne.jp'],
    ['hi-ho', 'hi-ho.ne.jp'],
    ['ASAHI ネット', 'asahi-net.or.jp'],
    ['mineo', 'mineo.jp'],
    ['楽天モバイル', 'rakumail.jp'],
    ['Outlook 日本', 'outlook.jp'],
    ['Hotmail 日本', 'hotmail.co.jp'],
    ['Live 日本', 'live.jp'],
    ['IIJ', 'iij.ad.jp'],
    ['DTI', 'dti.ne.jp'],
    ['WAKWAK', 'wakwak.com'],
    ['ODN', 'odn.ne.jp'],
    ['@nifty', 'nifty.ne.jp'],
    ['PDX', 'pdx.ne.jp'],
  ]),
  ...rows('韓國信箱', [
    ['Naver', 'naver.com'],
    ['Daum', 'daum.net'],
    ['Hanmail', 'hanmail.net'],
    ['Kakao', 'kakao.com'],
    ['Nate', 'nate.com'],
    ['Korea.com', 'korea.com'],
    ['Dreamwiz', 'dreamwiz.com'],
    ['Hanmir', 'hanmir.com'],
    ['Empal', 'empal.com'],
    ['Freechal', 'freechal.com'],
    ['Chol', 'chol.com'],
    ['Hanafos', 'hanafos.com'],
    ['Kornet', 'kornet.net'],
    ['Netian', 'netian.com'],
    ['Paran', 'paran.com'],
    ['Cyworld', 'cyworld.com'],
    ['Lycos 韓國', 'lycos.co.kr'],
    ['Yahoo 韓國', 'yahoo.co.kr'],
    ['Hotmail 韓國', 'hotmail.co.kr'],
    ['Unitel', 'unitel.co.kr'],
    ['Chollian', 'chollian.net'],
    ['Shinbiro', 'shinbiro.com'],
  ]),
  ...rows('歐洲信箱', [
    ['GMX 德國', 'gmx.de'],
    ['GMX.net', 'gmx.net'],
    ['GMX 奧地利', 'gmx.at'],
    ['GMX 瑞士', 'gmx.ch'],
    ['Web.de', 'web.de'],
    ['T-Online', 't-online.de'],
    ['Freenet', 'freenet.de'],
    ['Arcor', 'arcor.de'],
    ['Online.de', 'online.de'],
    ['1&1', '1und1.de'],
    ['IONOS', 'ionos.de'],
    ['Posteo', 'posteo.de'],
    ['Mailbox.org', 'mailbox.org'],
    ['Orange 法國', 'orange.fr'],
    ['Wanadoo', 'wanadoo.fr'],
    ['Free 法國', 'free.fr'],
    ['SFR', 'sfr.fr'],
    ['La Poste', 'laposte.net'],
    ['Neuf', 'neuf.fr'],
    ['Bbox', 'bbox.fr'],
    ['Voila', 'voila.fr'],
    ['Club Internet', 'club-internet.fr'],
    ['Alice 法國', 'aliceadsl.fr'],
    ['Libero', 'libero.it'],
    ['Virgilio', 'virgilio.it'],
    ['TIN', 'tin.it'],
    ['Alice 義大利', 'alice.it'],
    ['Tiscali 義大利', 'tiscali.it'],
    ['Fastweb', 'fastwebnet.it'],
    ['Poste Italiane', 'poste.it'],
    ['Email.it', 'email.it'],
    ['inwind', 'inwind.it'],
    ['IOL', 'iol.it'],
    ['TIM', 'tim.it'],
    ['Seznam', 'seznam.cz'],
    ['Email.cz', 'email.cz'],
    ['Centrum', 'centrum.cz'],
    ['Volny', 'volny.cz'],
    ['Atlas', 'atlas.cz'],
    ['WP.pl', 'wp.pl'],
    ['O2 波蘭', 'o2.pl'],
    ['Interia', 'interia.pl'],
    ['Onet', 'onet.pl'],
    ['Gazeta', 'gazeta.pl'],
    ['Tlen', 'tlen.pl'],
    ['Azet', 'azet.sk'],
    ['Centrum 斯洛伐克', 'centrum.sk'],
    ['Zoznam', 'zoznam.sk'],
    ['Skynet', 'skynet.be'],
    ['Telenet', 'telenet.be'],
    ['Proximus', 'proximus.be'],
    ['Pandora', 'pandora.be'],
    ['Ziggo', 'ziggo.nl'],
    ['KPN', 'kpnmail.nl'],
    ['Hetnet', 'hetnet.nl'],
    ['Planet', 'planet.nl'],
    ['XS4ALL', 'xs4all.nl'],
    ['Home.nl', 'home.nl'],
    ['Chello 荷蘭', 'chello.nl'],
    ['UPC', 'upcmail.nl'],
    ['Bluewin', 'bluewin.ch'],
    ['Sunrise', 'sunrise.ch'],
    ['Hispeed', 'hispeed.ch'],
    ['A1', 'a1.net'],
    ['Chello 奧地利', 'chello.at'],
    ['AON', 'aon.at'],
    ['Jubii', 'jubii.dk'],
    ['Sol.dk', 'sol.dk'],
    ['Stofanet', 'stofanet.dk'],
    ['Online.no', 'online.no'],
    ['Start.no', 'start.no'],
    ['Luukku', 'luukku.com'],
    ['Kolumbus', 'kolumbus.fi'],
    ['Saunalahti', 'saunalahti.fi'],
    ['Elisa', 'elisa.fi'],
    ['Suomi24', 'suomi24.fi'],
    ['Terra 西班牙', 'terra.es'],
    ['Telefónica', 'telefonica.net'],
    ['Ya.com', 'ya.com'],
    ['Movistar', 'movistar.es'],
    ['ONO', 'ono.com'],
    ['Jazztel', 'jazztel.es'],
    ['Eresmas', 'eresmas.com'],
    ['SAPO', 'sapo.pt'],
    ['Clix', 'clix.pt'],
    ['Netcabo', 'netcabo.pt'],
    ['Mail.ru 俄國', 'bk.ru'],
    ['List.ru', 'list.ru'],
    ['Inbox.ru', 'inbox.ru'],
    ['Rambler', 'rambler.ru'],
    ['Yandex 俄國', 'yandex.ru'],
    ['Ya.ru', 'ya.ru'],
    ['Ukr.net', 'ukr.net'],
    ['i.ua', 'i.ua'],
    ['Meta.ua', 'meta.ua'],
    ['Bigmir', 'bigmir.net'],
    ['ABV', 'abv.bg'],
    ['Mail.bg', 'mail.bg'],
    ['Dir.bg', 'dir.bg'],
    ['Inbox.lv', 'inbox.lv'],
    ['Inbox.lt', 'inbox.lt'],
    ['Freemail 匈牙利', 'freemail.hu'],
    ['Citromail', 'citromail.hu'],
    ['Otenet', 'otenet.gr'],
    ['in.gr', 'in.gr'],
    ['Yahoo 希臘', 'yahoo.gr'],
    ['BT', 'btinternet.com'],
    ['BT Openworld', 'btopenworld.com'],
    ['Talk21', 'talk21.com'],
    ['Virgin Media', 'virginmedia.com'],
    ['Blueyonder', 'blueyonder.co.uk'],
    ['NTLworld', 'ntlworld.com'],
    ['TalkTalk', 'talktalk.net'],
    ['Sky', 'sky.com'],
    ['Tiscali 英國', 'tiscali.co.uk'],
    ['Freeserve', 'freeserve.co.uk'],
    ['LineOne', 'lineone.net'],
    ['Plusnet', 'plusnet.com'],
    ['Eircom', 'eircom.net'],
    ['Indigo', 'indigo.ie'],
    ['Hotmail 英國', 'hotmail.co.uk'],
    ['Hotmail 法國', 'hotmail.fr'],
    ['Hotmail 德國', 'hotmail.de'],
    ['Hotmail 義大利', 'hotmail.it'],
    ['Hotmail 西班牙', 'hotmail.es'],
    ['Yahoo 英國', 'yahoo.co.uk'],
    ['Yahoo 法國', 'yahoo.fr'],
    ['Yahoo 德國', 'yahoo.de'],
    ['Yahoo 義大利', 'yahoo.it'],
    ['Yahoo 西班牙', 'yahoo.es'],
    ['Outlook 德國', 'outlook.de'],
    ['Outlook 法國', 'outlook.fr'],
    ['Outlook 西班牙', 'outlook.es'],
    ['Outlook 義大利', 'outlook.it'],
  ]),
  ...rows('美洲信箱', [
    ['Comcast', 'comcast.net'],
    ['Verizon', 'verizon.net'],
    ['AT&T', 'att.net'],
    ['SBC', 'sbcglobal.net'],
    ['Bellsouth', 'bellsouth.net'],
    ['Charter', 'charter.net'],
    ['Cox', 'cox.net'],
    ['EarthLink', 'earthlink.net'],
    ['MindSpring', 'mindspring.com'],
    ['PeoplePC', 'peoplepc.com'],
    ['Prodigy', 'prodigy.net'],
    ['Optimum', 'optonline.net'],
    ['Road Runner', 'roadrunner.com'],
    ['RR', 'rr.com'],
    ['Time Warner', 'twc.com'],
    ['Frontier', 'frontier.com'],
    ['Windstream', 'windstream.net'],
    ['CenturyLink', 'centurylink.net'],
    ['Q.com', 'q.com'],
    ['Suddenlink', 'suddenlink.net'],
    ['Mediacom', 'mediacom.net'],
    ['Cable One', 'cableone.net'],
    ['RCN', 'rcn.com'],
    ['HughesNet', 'hughes.net'],
    ['UOL', 'uol.com.br'],
    ['BOL', 'bol.com.br'],
    ['IG', 'ig.com.br'],
    ['Terra 巴西', 'terra.com.br'],
    ['Globo', 'globo.com'],
    ['GloboMail', 'globomail.com'],
    ['Oi', 'oi.com.br'],
    ['R7', 'r7.com'],
    ['Zipmail', 'zipmail.com.br'],
    ['Yahoo 巴西', 'yahoo.com.br'],
    ['Hotmail 巴西', 'hotmail.com.br'],
    ['Yahoo 墨西哥', 'yahoo.com.mx'],
    ['Prodigy 墨西哥', 'prodigy.net.mx'],
    ['Terra 墨西哥', 'terra.com.mx'],
    ['Live 墨西哥', 'live.com.mx'],
    ['Yahoo 阿根廷', 'yahoo.com.ar'],
    ['Fibertel', 'fibertel.com.ar'],
    ['Ciudad', 'ciudad.com.ar'],
    ['Yahoo 加拿大', 'yahoo.ca'],
    ['Sympatico', 'sympatico.ca'],
    ['Rogers', 'rogers.com'],
    ['Bell', 'bell.net'],
    ['Shaw', 'shaw.ca'],
    ['Telus', 'telus.net'],
    ['Videotron', 'videotron.ca'],
    ['Hotmail 加拿大', 'hotmail.ca'],
  ]),
  ...rows('東南亞信箱', [
    ['Yahoo 新加坡', 'yahoo.com.sg'],
    ['SingNet', 'singnet.com.sg'],
    ['Pacific 新加坡', 'pacific.net.sg'],
    ['StarHub', 'starhub.net.sg'],
    ['Yahoo 馬來西亞', 'yahoo.com.my'],
    ['TM', 'tm.net.my'],
    ['Streamyx', 'streamyx.com'],
    ['Yahoo 印尼', 'yahoo.co.id'],
    ['Plasa', 'plasa.com'],
    ['Telkom', 'telkom.net'],
    ['Yahoo 菲律賓', 'yahoo.com.ph'],
    ['Yahoo 越南', 'yahoo.com.vn'],
    ['VNN', 'vnn.vn'],
    ['FPT', 'fpt.vn'],
    ['Yahoo 泰國', 'yahoo.co.th'],
    ['Hotmail 泰國', 'hotmail.co.th'],
    ['True', 'truemail.co.th'],
    ['Rediffmail', 'rediffmail.com'],
    ['Sify', 'sify.com'],
    ['IndiaTimes', 'indiatimes.com'],
    ['Yahoo 印度', 'yahoo.co.in'],
    ['BSNL', 'bsnl.in'],
    ['Sancharnet', 'sancharnet.in'],
    ['Outlook 新加坡', 'outlook.sg'],
    ['Outlook 馬來西亞', 'outlook.my'],
    ['Outlook 印尼', 'outlook.co.id'],
  ]),
  ...rows('大洋洲信箱', [
    ['BigPond', 'bigpond.com'],
    ['BigPond 網域', 'bigpond.net.au'],
    ['Optus', 'optusnet.com.au'],
    ['iiNet', 'iinet.net.au'],
    ['TPG', 'tpg.com.au'],
    ['Westnet', 'westnet.com.au'],
    ['Internode', 'internode.on.net'],
    ['Dodo', 'dodo.com.au'],
    ['OzEmail', 'ozemail.com.au'],
    ['Yahoo 澳洲', 'yahoo.com.au'],
    ['Hotmail 澳洲', 'hotmail.com.au'],
    ['Outlook 澳洲', 'outlook.com.au'],
    ['Xtra', 'xtra.co.nz'],
    ['Clear', 'clear.net.nz'],
    ['Paradise', 'paradise.net.nz'],
    ['Slingshot', 'slingshot.co.nz'],
    ['Orcon', 'orcon.net.nz'],
    ['Yahoo 紐西蘭', 'yahoo.co.nz'],
    ['Outlook 紐西蘭', 'outlook.co.nz'],
  ]),
  ...rows('隱私信箱', [
    ['ProtonMail', 'protonmail.com'],
    ['Proton 短址', 'pm.me'],
    ['Proton 瑞士', 'protonmail.ch'],
    ['Tuta', 'tuta.com'],
    ['Tutanota', 'tutanota.com'],
    ['Tutanota 德國', 'tutanota.de'],
    ['KeeMail', 'keemail.me'],
    ['Disroot', 'disroot.org'],
    ['Riseup', 'riseup.net'],
    ['Autistici', 'autistici.org'],
    ['Inventati', 'inventati.org'],
    ['systemli', 'systemli.org'],
    ['immerda', 'immerda.ch'],
    ['DuckDuckGo', 'duck.com'],
    ['Firefox Relay', 'mozmail.com'],
    ['Hush.com', 'hush.com'],
  ]),
  ...rows('轉寄信箱', [
    ['Apple 隱藏郵件', 'privaterelay.appleid.com'],
    ['SimpleLogin', 'simplelogin.com'],
    ['SimpleLogin 法國', 'simplelogin.fr'],
    ['SimpleLogin 短址', 'simplelogin.co'],
    ['Aleeas', 'aleeas.com'],
    ['Addy', 'addy.io'],
    ['AnonAddy', 'anonaddy.com'],
    ['AnonAddy Me', 'anonaddy.me'],
    ['33Mail', '33mail.com'],
  ]),
  ...rows('臨時信箱', [
    ['Mailinator', 'mailinator.com'],
    ['Mailinator 網域', 'mailinator.net'],
    ['Yopmail', 'yopmail.com'],
    ['Yopmail 法國', 'yopmail.fr'],
    ['Guerrilla Mail', 'guerrillamail.com'],
    ['Sharklasers', 'sharklasers.com'],
    ['grr.la', 'grr.la'],
    ['Guerrilla 德國', 'guerrillamail.de'],
    ['Guerrilla 資訊', 'guerrillamail.info'],
    ['Spam4', 'spam4.me'],
    ['TrashMail', 'trashmail.com'],
    ['Dispostable', 'dispostable.com'],
    ['Nada', 'getnada.com'],
    ['Moakt', 'moakt.com'],
    ['10 Minute Mail', '10minutemail.com'],
    ['Mailnesia', 'mailnesia.com'],
    ['Discard', 'discard.email'],
    ['Maildrop', 'maildrop.cc'],
    ['SpamGourmet', 'spamgourmet.com'],
    ['Binkmail', 'binkmail.com'],
    ['Bobmail', 'bobmail.info'],
    ['Throwaway', 'throwawaymail.com'],
  ]),
  ...rows('學校信箱', [
    ['MIT', 'mit.edu'],
    ['Stanford', 'stanford.edu'],
    ['Harvard', 'harvard.edu'],
    ['Berkeley', 'berkeley.edu'],
    ['台大', 'ntu.edu.tw'],
    ['清大', 'nthu.edu.tw'],
    ['成大', 'ncku.edu.tw'],
    ['陽明交大', 'nycu.edu.tw'],
    ['政大', 'nccu.edu.tw'],
    ['港大', 'hku.hk'],
    ['中大', 'cuhk.edu.hk'],
    ['科大', 'ust.hk'],
    ['東京大學', 'u-tokyo.ac.jp'],
    ['京都大學', 'kyoto-u.ac.jp'],
    ['首爾大學', 'snu.ac.kr'],
    ['KAIST', 'kaist.ac.kr'],
    ['Oxford', 'ox.ac.uk'],
    ['Cambridge', 'cam.ac.uk'],
    ['ETH', 'ethz.ch'],
    ['TUM', 'tum.de'],
    ['墨爾本大學', 'unimelb.edu.au'],
    ['台科大', 'ntust.edu.tw'],
  ]),
  ...rows('中東信箱', [
    ['Walla', 'walla.co.il'],
    ['Walla.com', 'walla.com'],
    ['Bezeq', 'bezeqint.net'],
    ['012', '012.net.il'],
    ['Maktoob', 'maktoob.com'],
    ['Yahoo 以色列', 'yahoo.co.il'],
  ]),
  ...rows('非洲信箱', [
    ['MWEB', 'mweb.co.za'],
    ['Telkom', 'telkomsa.net'],
    ['Vodamail', 'vodamail.co.za'],
    ['Yahoo 南非', 'yahoo.co.za'],
    ['iafrica', 'iafrica.com'],
    ['Absa', 'absamail.co.za'],
    ['Webmail 南非', 'webmail.co.za'],
  ]),
];

const PEOPLE: Array<{ name: string; local: string }> = [
  { name: '林可恩', local: 'linkeen' },
  { name: '陳安然', local: 'chenanran' },
  { name: '王明哲', local: 'wangmingzhe' },
  { name: '李華', local: 'lihua' },
  { name: '張寧', local: 'zhangning' },
  { name: '黃詩涵', local: 'huangshihan' },
  { name: '吳恩佑', local: 'wuenyou' },
  { name: '蔡雅筑', local: 'caiyazhu' },
  { name: '劉洋', local: 'liuyang' },
  { name: '許真', local: 'xuzhen' },
  { name: '鄭凱', local: 'zhengkai' },
  { name: '謝宜君', local: 'xieyijun' },
  { name: '周子豪', local: 'zhouzihao' },
  { name: '葉安', local: 'yean' },
  { name: '潘寧', local: 'panning' },
  { name: '蘇雅婷', local: 'suyating' },
  { name: '高恩齊', local: 'gaoenqi' },
  { name: '羅真', local: 'luozhen' },
];

const HOT = new Set([
  'gmail.com', 'outlook.com', 'hotmail.com', 'live.com', 'yahoo.com', 'icloud.com',
  'qq.com', '163.com', '126.com', 'foxmail.com', 'sina.com', 'sohu.com',
  'yahoo.com.tw', 'hinet.net', 'yahoo.com.hk', 'yahoo.co.jp', 'docomo.ne.jp',
  'ezweb.ne.jp', 'softbank.ne.jp', 'naver.com', 'daum.net', 'hanmail.net',
  'aol.com', 'gmx.de', 'web.de', 'proton.me', 'protonmail.com', 'comcast.net',
]);

const WARM = new Set([
  'googlemail.com', 'msn.com', 'ymail.com', 'rocketmail.com', 'me.com', 'mac.com',
  'yeah.net', '139.com', '189.cn', '21cn.com', 'tom.com', 'aliyun.com',
  'seed.net.tw', 'pchome.com.tw', 'i.softbank.jp', 'kakao.com', 'nate.com',
  'outlook.jp', 'hotmail.co.uk', 'yahoo.co.uk', 'hotmail.fr', 'hotmail.de',
  'libero.it', 'orange.fr', 'free.fr', 'laposte.net', 'btinternet.com', 'sky.com',
  'att.net', 'verizon.net', 'gmx.com', 'zoho.com', 'hey.com', 'fastmail.com',
  'mail.ru', 'yandex.com', 'yandex.ru', 'uol.com.br', 'yahoo.com.au', 'bigpond.com',
  'ocn.ne.jp', 'biglobe.ne.jp', 'nifty.com',
]);

export function copiesFor(domain: string): number {
  if (HOT.has(domain)) return 15;
  if (WARM.has(domain)) return 6;
  return 3;
}

export function mailCasePeople(domain: string, index: number): Array<{ name: string; email: string }> {
  const count = copiesFor(domain);
  return Array.from({ length: count }, (_, personIndex) => {
    const person = PEOPLE[(index + personIndex) % PEOPLE.length];
    if (!person) throw new Error('人名清單是空的');
    return { name: person.name, email: `${person.local}@${domain}` };
  });
}

export function duplicateMailDomains(cases: MailCase[] = MAIL_CASES): string[] {
  const seen = new Set<string>();
  const dupes: string[] = [];
  for (const item of cases) {
    if (seen.has(item.domain)) dupes.push(item.domain);
    seen.add(item.domain);
  }
  return dupes;
}
